### ISSUE TITLE
Android Port

### ISSUE THREAD

**Issue by Thanson16** [xtreme8000/aof-opengl#104]
Hey there, currently an OpenSpades user, but I see you have a Google Play Store link on the top of the README. It seems to be broken, so my questions:

- Will this ever be back on the Play Store?
- Is there a way to compile the APK myself?

Super interested in the idea of being able to play Spades on my mobile device, and even better if I don't have to get it through the Play store (custom ROM). I'd appreciate any info I could get on the matter.

Thank you guys for all the work you do. Much appreciated.

**Comment by xtreme8000** [comment]
* Yes, I plan to bring BS back to the play store some time.
* You can try, but it is quite hard due to Android's build system and the dependencies you need to link in.
  You can start from a clean SDL2 android project and go from there by adding BS's source and at least ENet and libdeflate. I put all three of them as their own modules in the ndk project, using the ndk's plain make system. Then define the required macros for an android build and it "should work already" *(There is also a special assets folder location that SDL2 uses where you can put all game assets)*. Honestly I can't describe it much better without going very much in depth here, as I only have an android studio project myself that I crudely glued together to get it to work.

The reason why I haven't spent much time bringing it back is that it was quite unplayable due to the nature of touch screens and their controls issue. There are quite many buttons to map to the screen in a game as AoS, which makes it very hard to play on a small screen.

**Comment by Thanson16** [comment]
Thanks for the information!

I probably won't have the time to try and compile myself any time soon then, but if you ever want someone to test APK's, shoot me an email or a message on matrix (@thor:thorjhanson.com).

It'd be really cool if some work could be done controls-wise to come up with an intuitive way of playing the game on mobile - wish I had the time to help in that respect, but we'll see.
