### ISSUE TITLE
Incorrect ammo and HP counters displayed when spectating someone

### ISSUE THREAD

**Issue by JimPix1** [xtreme8000/aof-opengl#162]
When you spectate a player in BetterSpades, the ammo and HP indicators are displayed on-screen but are always full/the default even if the person you're spectating does not have full ammo or full HP. Essentially, the indicators are pointless and shouldn't be there. It would be better to remove them while in spectator mode.

**Comment by dany-on-demand** [comment]
Update on this: ammo is shown correctly, but HP isn't. OpenSpades doesn't show ammo or hp while spectating

![image](https://github.com/xtreme8000/BetterSpades/assets/1732765/f06d460a-f921-4ce4-8006-e0a0ce777055)
![image](https://github.com/xtreme8000/BetterSpades/assets/1732765/1544cb59-2cfb-42ec-90ac-f5434faca2fa)
![image](https://github.com/xtreme8000/BetterSpades/assets/1732765/68ea9d90-0a39-4620-b3a5-78eb859ba6f4)
![image](https://github.com/xtreme8000/BetterSpades/assets/1732765/c61b7c4c-9787-4d7a-8648-006aa6bc53af)

**Comment by dany-on-demand** [comment]
Ah, I figured out what the issue is. The issue is that when the player's ammo was spent BEFORE connecting to the server, then if you join internally the client thinks the player has full ammo. If that players shoots/spends ammo or if it's reset by the server (I tested on a tent), then this does get reflected, as in the ammo will be subtracted, but from the starting position of full ammo, so it will still be incorrect. In which case I'd suggest doing the same thing OpenSpades does - simply hiding the ammo/hp. And as Jim pointed out, theoretically players could use this to cheat in for example arena mode (even though I'd say it's quite a stretch). We can keep the code which keeps track of this in spectator. As this is a "bug" in the protocol, this can be fixed later
